### ISSUE TITLE
pcl_post_preprocessing potentially ignoring part of the filtering pipeline

### ISSUE THREAD

**Issue by evbernardes** [dwjoris/XRTwin_CAD_model_alignment#5]
@Menthy-Denayer In the main function of the file [pcl_post_processing.py](https://github.com/dwjoris/XRTwin_CAD_model_alignment/blob/main/h5_files/pcl_post_processing.py), I think that the following line:
```Python
inside_rect = inside_rectangle(pcd, corners_obb, draw=draw)
```
Should be replaced by:
```Python
inside_rect = inside_rectangle(cl, corners_obb, draw=draw)
```
Since `pcd` is just the input point cloud while `cl` is the output of `remove_outliers`. Do you agree with this?

**Comment by Menthy-Denayer** [comment]
Yes, indeed that should be changed. The pcl_post_procesing.py file has a few lines of code that can be swapped out and changed, depending on the case. Sometimes it can be useful to swap/leave out some steps to obtain a better result. It is best to check the results for every case, as some tweaks might be required to improve the cutout.
